name: Lint

on:
  - push
  - pull_request

permissions:
  contents: read
  pull-requests: read

jobs:
  lint-ruff:
    strategy:
      matrix:
        python-version: [ '3.12' ]
    name: Ty Type Checking
    uses: SanctumLabs/ci-workflows/.github/workflows/python-lint.yml@main
    with:
      command: make lint-ruff
      python-version: ${{ matrix.python-version }}
      packager: uv

  lint-ty:
    strategy:
      matrix:
        python-version: [ '3.12' ]
    name: Ty Type Checking
    uses: SanctumLabs/ci-workflows/.github/workflows/python-lint.yml@main
    with:
      command: make ty-check
      python-version: ${{ matrix.python-version }}
      packager: uv

  lint-pyrefly:
    strategy:
      matrix:
        python-version: [ '3.12' ]
    name: Flake8
    uses: SanctumLabs/ci-workflows/.github/workflows/python-lint.yml@main
    with:
      command: make pyrefly-check
      python-version: ${{ matrix.python-version }}
      packager: uv